name: CI Pipeline
#happens whenever the code is pushed or when it is pulled
on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    # starts a temporary postgres server
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    #pulls the latest code
      - name: Checkout repository
        uses: actions/checkout@v4
    #installs nodejs version which is 20
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
    #install project dependecies which is from the package.json
      - name: Install dependencies
        run: npm ci
  #generates the prisma client based on the schema
      - name: Generate Prisma Client
        run: npx prisma generate
  # runs all the database migration to the temp database
      - name: Run Prisma migrations (test DB)
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
        run: npx prisma migrate deploy
  #runs eslint to check coding sytle and catch errors early if there is anny
      - name: Run ESLint
        run: npm run lint
#runs any unit test if there is any, hwoever, if none then message is formed
      - name: Run unit tests (if any)
        run: npm test || echo "No tests found"
