name: Deploy Taskify to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Prepare build directory
        run: |
          mkdir build
          cp package.json build/
          cp package-lock.json build/
          cp -r prisma build/
          cp -r src build/
          cp -r node_modules build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: taskify-build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B4DEB4821E3847958F1DF97C0FD660ED }}
          tenant-id:  ${{ secrets.AZUREAPPSERVICE_TENANTID_901ECBEC6F134D41B1A93A389F10381F }}
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F1A9DE9A0ED24F4AA76175FC81BE592F}}
          

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: Taskify
          package: taskify-build




